build: Suppress cppcheck false-positive on array bounds
Cppcheck 2.6 reports the following errors, when loops on arrays depend
on a sentinel:

 trust/builder.c:1103,error,arrayIndexOutOfBounds,Array 'schema->attrs[32]' accessed at index 9998, which is out of bounds.
 trust/builder.c:1136,error,arrayIndexOutOfBounds,Array 'schema->attrs[32]' accessed at index 9998, which is out of bounds.
 trust/builder.c:1301,error,arrayIndexOutOfBounds,Array 'ku_attribute_map[8]' accessed at index 9998, which is out of bounds.
 trust/builder.c:1385,error,arrayIndexOutOfBounds,Array 'eku_attribute_map[9]' accessed at index 9998, which is out of bounds.

This adds an extra check to those loop conditions.  While it is
redundant, this should be harmless as it is not in the performance
critical path.

Signed-off-by: Daiki Ueno <ueno@gnu.org>