build: Fix linker errors on macOS
This fixes a few linker errors on macOS due to an undefined
p11_library_mutex symbol:

| cc  -o p11-kit/p11-kit-server-testable p11-kit/p11-kit-server-testable.p/server.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -Wl,-rpath,/opt/local/lib p11-kit/libp11-kit-testable.a common/libp11-library.a common/libp11-common.a common/libp11-tool.a /opt/local/lib/libffi.dylib
| Undefined symbols for architecture x86_64:
|   "_p11_library_mutex", referenced from:
|       _p11_kit_be_quiet in libp11-kit-testable.a(util.c.o)
|       _p11_kit_be_loud in libp11-kit-testable.a(util.c.o)
|       _p11_kit_set_progname in libp11-kit-testable.a(util.c.o)
| ld: symbol(s) not found for architecture x86_64

Fix these by using meson's link_whole feature where required. Note that
instead of declaring a sepearate dependency with link_whole, we could
have used .as_link_whole() on the existing dependency object, but that
would have required bumping the minimum meson version to 0.56. We
decided not to do this for not for compatibility reasons.

Signed-off-by: Clemens Lang <cllang@redhat.com>